ALTER TABLE claim_requests
ADD COLUMN nomor_whatsapp VARCHAR(20) NOT NULL,
ADD COLUMN email VARCHAR(100) NOT NULL,
ADD COLUMN is_liked BOOLEAN DEFAULT FALSE,
ADD COLUMN is_comment BOOLEAN DEFAULT FALSE,
ADD COLUMN is_shared BOOLEAN DEFAULT FALSE,
ADD COLUMN is_follow BOOLEAN DEFAULT FALSE;